name: Publish release artifacts

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release git tag
        type: string
        required: true
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: [ "11.2.1" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Ghidra ${{ matrix.ghidra }}
        uses: antoniovazquezblanco/setup-ghidra@v2.0.6
        with:
          version: ${{ matrix.ghidra }}

      - name: Build extension
        run: ./gradlew

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          overwrite: true
          name: SwitchLoader
          path: dist/SwitchLoader-*.zip